set(CMAKE_C_CREATE_STATIC_LIBRARY
    "<CMAKE_LINKER> /lib /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_CREATE
    "<CMAKE_AR> /lib /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "")

set(CMAKE_CXX_CREATE_STATIC_LIBRARY
    "<CMAKE_LINKER> /lib /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_CREATE
    "<CMAKE_AR> /lib /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH "")
